### ISSUE TITLE
Error: Is not supported by any available resolver

### ISSUE THREAD

**Issue by vinnymac** [toss/yarn-plugin-catalogs#10]
Thanks for the plugin, great idea and apologies if this is something simple I am missing. For context, I have a turborepo with some packages/ and apps/ which each have there own package.json files. The root of the project also includes a package.json. I followed the readme and installed the plugin without issue, running yarn works fine after import. Then I updated my `.yarnrc.yml` to include catalogs, here is the contents of that file:

```yml
plugins:
  - checksum: 838ea0b9eba0ecc08de1ee074d49f655e912a2b0190911c69711c13b930617e6dd0904eaa9123163f885709a060dbba294bd60866503b3de1d681a568ce4120e
    path: .yarn/plugins/@yarnpkg/plugin-catalogs.cjs
    spec: 'https://raw.githubusercontent.com/toss/yarn-plugin-catalogs/main/bundles/%40yarnpkg/plugin-catalogs.js'

catalogs:
  list:
    # Root catalogs (can be referenced with just "catalog:")
    typescript: 5.8.3
```

I then updated my package.json files to reference the catalog with `"typescript": "catalog:"`. Finally I ran `yarn`, and received this error:
```log
$ yarn
➤ YN0000: · Yarn 4.9.1-git.20250411.hash-1908ee79f
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: typescript@catalog: isn't supported by any available resolver
    at rm.getResolverByDescriptor (/Users/vinnymac/.volta/tools/image/yarn/4.9.1/bin/yarn.js:141:1698)
    at rm.bindDescriptor (/Users/vinnymac/.volta/tools/image/yarn/4.9.1/bin/yarn.js:141:1083)
    at /Users/vinnymac/.volta/tools/image/yarn/4.9.1/bin/yarn.js:210:8315
    at Array.map (<anonymous>)
    at gt (/Users/vinnymac/.volta/tools/image/yarn/4.9.1/bin/yarn.js:210:8286)
    at /Users/vinnymac/.volta/tools/image/yarn/4.9.1/bin/yarn.js:210:8998
    at async Promise.allSettled (index 0)
    at async Uu (/Users/vinnymac/.volta/tools/image/yarn/4.9.1/bin/yarn.js:140:53356)
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 0s 178ms
```

Any idea what I am doing wrong?
